#! /usr/bin/env python
# coding:utf-8
__author__ = 'Farley'

import unittest
from common.read_excel import *
from common.read_sql import *
import requests
from model.log import logger
import json

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class checkNewVersion(unittest.TestCase):

    def setUp(self):
        pass

    def test_001(self):
        '''检测新版本'''
        logger.info('正在读取_{0}s:test_001...'.format(os.path.basename(os.path.abspath(__file__))))
        url = selectMysql('Requst_URL','chemi_interface_case', 2)[0]
        body = selectMysql('Request_Data','chemi_interface_case', 2)[0]
        r = requests.post(url=url, data=body)
        responds = r.json()
        check_point = responds['code']
        check_point_msg = responds['msg']
        print(check_point)
        print(r.text)
        assert check_point == 200 and check_point_msg == u'执行成功'
        logger.info("%s:test__001测试结果正在写入数据库..."%os.path.basename(os.path.abspath(__file__)))
        if check_point == 200:
            updataMysql('chemi_interface_case',r.text, 'pass', '检测新版本')
        else:
            updataMysql('chemi_interface_case',r.text, 'fail', '检测新版本')
        logger.info('%s:test_001执行完毕.'%os.path.basename(os.path.abspath(__file__)))

    def tearDown(self):
        pass

if __name__ == '__main':
    it = checkNewVersion()
    it.test_001()
